GO := go
TESTFILE    := _testok

GOLANG_CI				:= github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.9.0
GOFUMPT					:= mvdan.cc/gofumpt@latest
GOVULNCHECK				:= golang.org/x/vuln/cmd/govulncheck@latest
GOIMPORTS 				:= golang.org/x/tools/cmd/goimports@latest
GOTESTSUM				:= gotest.tools/gotestsum@v1.13.0

# Generate labels for all language runtimes
.PHONY: generate
generate: fmt

.PHONY: install-tools
install-tools:
	$(GO) install $(GOTESTSUM)
	$(GO) install $(GOIMPORTS)


.PHONY: lint
lint: fmt ## Run linters on all go files
	$(GO) run $(GOLANG_CI) run -v ./...


.PHONY: fmt
fmt: install-tools ## Formats all go files
	$(GO) run $(GOFUMPT) -l -w -extra  .
	find . -type f -name '*.go' -exec grep -L -E 'Code generated by .*\. DO NOT EDIT.' {} + | xargs goimports -format-only -w -local=github.com/rudderlabs

test: install-tools test-run test-teardown

test-run: ## Run all unit tests
	$(eval TEST_CMD = gotestsum --format pkgname-and-test-fails --)
	$(eval TEST_OPTIONS = -race -p=1 -v -failfast -shuffle=on -coverprofile=profile.out -covermode=atomic -coverpkg=./... -vet=all --timeout=15m)
ifdef package
ifdef exclude
	$(eval FILES = `go list ./$(package)/... | egrep -iv '$(exclude)'`)
	$(TEST_CMD) -count=1 $(TEST_OPTIONS) $(FILES) && touch $(TESTFILE) || true
else
	$(TEST_CMD) $(TEST_OPTIONS) ./$(package)/... && touch $(TESTFILE) || true
endif
else ifdef exclude
	$(eval FILES = `go list ./... | egrep -iv '$(exclude)'`)
	$(TEST_CMD) -count=1 $(TEST_OPTIONS) $(FILES) && touch $(TESTFILE) || true
else
	$(TEST_CMD) -count=1 $(TEST_OPTIONS) ./... && touch $(TESTFILE) || true
endif

test-teardown:
	@if [ -f "$(TESTFILE)" ]; then \
    	echo "Tests passed, tearing down..." ;\
		rm -f $(TESTFILE) ;\
		echo "mode: atomic" > coverage.txt ;\
		find . -name "profile.out" | while read file; do grep -v 'mode: atomic' $${file} >> coverage.txt; rm -f $${file}; done ;\
	else \
    	rm -f coverage.txt coverage.html ; find . -name "profile.out" | xargs rm -f ;\
		echo "Tests failed :-(" ;\
		exit 1 ;\
	fi

coverage: ## Generate HTML coverage report
	$(GO) tool cover -html=coverage.txt -o coverage.html

test-with-coverage: test coverage